### PR TITLE
Create team_norms_playbook.md

### PR DESCRIPTION
**Pull request by cehopkins3**

### CODE REVIEW

**Comment by tgaff** [comment]
FYI: README.md was moved to index.md to support the guides.labzero.com site.  

I'm happy to update that here before merge but I'm waiting on responses from Dean in a thread in the product channel.

**Review by rdeanbaker — COMMENTED** [review]
minor optional suggestions to tweak. fine with it as-is for now.

**Comment by tgaff** [comment]
@rdeanbaker I believe I have resolved all of your requested changes.  I've also corrected this so it can cleanly merge to master.

**Review by rdeanbaker — APPROVED** [review]
looks good, thanks

**Pull request merged**
