### PR TITLE
setup github-pages site for guides

### PR DESCRIPTION
**Pull request by tgaff**
We currently use the guides as-is on github.  This PR turns them into a nicely formatted github pages site with hopefully a better user experience for those who may not be familiar with Github.  This PR sets that up (aside from the github setting) and makes some initial decisions on look and design.  In short Github automates the deploy and hosting for us; this just sets some config and adapts to the slightly different rules for gh-pages.

Once this is merged I'll make a config change and the site will render at https://labzero.github.io/guides

For now you can see what it will look like here: https://tgaff.github.io/lzguides/ (will delete this later)

In order to keep this as easy to work on as possible, nearly everything has remained as plain markdown.  There are only a few cases where jekyll/liquid code was used.  

Remaining TODOs (will likely be new PRs):

* comb through each page and update links to be correct in the GH-pages context - _95% ready to PR once this merges_
* v̶e̶r̶i̶f̶y̶ ̶t̶h̶e̶ ̶i̶m̶a̶g̶e̶ ̶u̶s̶e̶d̶ ̶i̶s̶ ̶O̶K̶ - confirmed by Dean & CG
* move images to a shared assets directory
* check in with someone in design and see if there's anything here they think needs to be changed
* add Google Analytics code for metrics

### CODE REVIEW

**Review by mjelks — APPROVED** [review]
This looks really good to me. Ideally I'd like another dev to have a look and confirm we're ok. I see that we have sign-off from CG and Dean re: design so I have no objections there.

**Comment by tgaff** [comment]
> This looks really good to me. Ideally I'd like another dev to have a look and confirm we're ok. I see that we have sign-off from CG and Dean re: design so I have no objections there.

wait... where are you seeing this?  I haven't been involved in that.

**Review by holetse — APPROVED** [review]
Looks good!

**Review by holetse — APPROVED** [review]
Re-approving!

**Comment by tgaff** [comment]
thank you!

**Pull request merged**
